export const dynamicCard = [
  {
    id: "1",
    name: "General Chat",
    src: "Chat",
    content: `This page allows users to engage with the model freely, capturing interactions efficiently in an ordered tree format. Not associated with specific tasks, it facilitates seamless user interaction.  Additionally, it integrates Indic Xlit for multilingual support. Users can edit previous prompt rate outputs. The page also offers options to end or start a new chat, displays conversation history in a side panel, and allows users to select the language for the chat input box.`,
  },
  {
    id: "2",
    name: "Instruction Driven Chat",
    src: "IntegrationInstructions",
    content: `This offers guided interactions with the model, incorporating general chat components and instructional prompts to engage users effectively. Real-time prompt checking includes language, intent, domain, and duplicate checks to ensure accuracy. Users may request hints for improved understanding and utilize a task timer display to monitor interaction duration. Inline annotation enables editing model outputs, with edited outputs applied in subsequent interactions.`,
  },
  {
    id: "3",
    name: "Rate Model Response",
    src: "RateReview",
    content: `It primarily generates SFT data, presenting users with prompts and model outputs. Optionally, instructions are provided. Users can edit prompts and outputs, and create new prompt/response pairs if desired, potentially guided by instructions. Features include editable text areas for prompt, output, and optional instruction. Side panel displays pending and completed tasks. Form captures user edits and general quality remarks. Task timer indicates user time spent.`,
  },
  {
    id: "4",
    name: "Model Response Evaluation",
    src: "QuestionAnswer",
    content: `It acts as a platform for evaluating model responses to prompts. Users review both prompts and corresponding outputs, offering scores using a likert scale or completing a questionnaire. To aid evaluation, a track bar enables users to score outputs, while a form facilitates detailed feedback submission for each prompt-output pair. This streamlined design enhances efficiency and effectiveness, fostering user engagement and comprehensive feedback generation.`,
  },
  {
    id: "5",
    name: "Preference Ranking",
    src: "Compare",
    content: `Users engage with prompts and multiple outputs, sourced from various models, for preference ranking. Two screens are provided, namely N-Output Preference Screen, in which the users rank N prompts by preference and Dual Output Preference Screen in which users choose between two outputs, that have been generated by the models for the same prompt. They can add comments explaining their choice and select additional options  for feedback submission.`,
  },
  {
    id: "6",
    name: "Analytics",
    src: "PsychologyAlt",
    content: `Users access customized analytics for their activity, language trends, and platform performance. User-specific analytics offer productivity insights, including task completion and average time per task. Language-specific analytics offer task completion and time allocation insights. Users analyze task distribution and average time spent per task. Globally, users gain insights into platform activity, including completed tasks and aggregated data, providing performance trends.`,
  },
];

export const footer ={
  content: 'ANUDESH - Developed at AI4Bharat Lab'
};

export const operationalModes = {
  heading: 'Operational Modes',
  admin_mode: 'Admin Mode',
  admin_content: 'In admin mode, efficient task management is enabled, allowing for the creation of diverse tasks which can be allocated seamlessly to user groups. Questionnaire customization within task contexts enhances adaptability, alongwith advanced analytics tools for strategic decision-making.',
  user_mode: 'User Mode',
  user_content: 'In user mode, participants engage in projects spanning various organizations, adopting roles like annotator, reviewer, or superchecker. They offer feedback per prompt, response, and model through our structured questionnaire system.'
};

export const info = {
  question: 'What is Anudesh',
  subquestion: 'Who We Are?',
  content: 'Anudesh is an open-source platform dedicated to advancing the development of state-of-the-art Language Model Models for Indian languages. Our mission is to democratize access to advanced natural language processing technologies by creating high-quality conversational data. By contributing to Anudesh, you can play a vital role in enhancing language understanding and generation capabilities in Indian languages. Whether you are a linguist, developer, or language enthusiast, there are many ways to get involved and make an impact. Join us in our journey to empower individuals and communities through language technology. Get started today by exploring our projects, contributing to our repositories, or joining our community discussions. We look forward to collaborating with you!'
};

export const banner = {
  heading: 'Anudesh : An Initiative to source better data by AI4Bharat',
  subheading: 'Contribute to the development of state of the art LLMs for Indian languages by helping us create high quality conversational data.',
  demo: 'Demo Video',
  logIn: 'Sign In/Sign Up',
  chat: 'Chat Page',
};