export const dummyData = {
  InstructionDrivenChat: [
    { language: "Assamese", ann_cumulative_tasks_count: 48061, rew_cumulative_tasks_count: 34454 },
    { language: "Bengali", ann_cumulative_tasks_count: 44033, rew_cumulative_tasks_count: 38650 },
    { language: "Bodo", ann_cumulative_tasks_count: 40306, rew_cumulative_tasks_count: 27491 },
    { language: "Dogri", ann_cumulative_tasks_count: 12955, rew_cumulative_tasks_count: 11809 },
    { language: "Gujarati", ann_cumulative_tasks_count: 4487, rew_cumulative_tasks_count: 3112 },
    { language: "Hindi", ann_cumulative_tasks_count: 38688, rew_cumulative_tasks_count: 25073 },
    { language: "Kannada", ann_cumulative_tasks_count: 31785, rew_cumulative_tasks_count: 26537 },
    { language: "Kashmiri", ann_cumulative_tasks_count: 21729, rew_cumulative_tasks_count: 19480 },
    { language: "Konkani", ann_cumulative_tasks_count: 15803, rew_cumulative_tasks_count: 14824 },
    { language: "Maithili", ann_cumulative_tasks_count: 29316, rew_cumulative_tasks_count: 28301 },
    { language: "Malayalam", ann_cumulative_tasks_count: 34692, rew_cumulative_tasks_count: 30769 },
    { language: "Manipuri", ann_cumulative_tasks_count: 8776, rew_cumulative_tasks_count: 5839 },
    { language: "Marathi", ann_cumulative_tasks_count: 25554, rew_cumulative_tasks_count: 20764 },
    { language: "Nepali", ann_cumulative_tasks_count: 50097, rew_cumulative_tasks_count: 42414 },
    { language: "Odia", ann_cumulative_tasks_count: 34643, rew_cumulative_tasks_count: 23782 },
    { language: "Others", ann_cumulative_tasks_count: 42054, rew_cumulative_tasks_count: 0 },
    { language: "Punjabi", ann_cumulative_tasks_count: 32250, rew_cumulative_tasks_count: 25603 },
    { language: "Sanskrit", ann_cumulative_tasks_count: 22916, rew_cumulative_tasks_count: 21277 },
    { language: "Santali", ann_cumulative_tasks_count: 21077, rew_cumulative_tasks_count: 17984 },
    { language: "Sindhi", ann_cumulative_tasks_count: 19465, rew_cumulative_tasks_count: 15318 },
    { language: "Tamil", ann_cumulative_tasks_count: 77294, rew_cumulative_tasks_count: 73697 },
    { language: "Telugu", ann_cumulative_tasks_count: 44360, rew_cumulative_tasks_count: 42235 },
    { language: "Urdu", ann_cumulative_tasks_count: 39537, rew_cumulative_tasks_count: 37244 },
  ],
  ModelInteractionEvaluation: [
    { language: "English", ann_cumulative_tasks_count: 10, rew_cumulative_tasks_count: 10 },
    { language: "Gujarati", ann_cumulative_tasks_count: 83, rew_cumulative_tasks_count: 0 },
    { language: "Hindi", ann_cumulative_tasks_count: 519, rew_cumulative_tasks_count: 53 },
    { language: "Konkani", ann_cumulative_tasks_count: 6542, rew_cumulative_tasks_count: 0 },
    { language: "Malayalam", ann_cumulative_tasks_count: 284, rew_cumulative_tasks_count: 0 },
    { language: "Marathi", ann_cumulative_tasks_count: 1991, rew_cumulative_tasks_count: 0 },
    { language: "Odia", ann_cumulative_tasks_count: 329, rew_cumulative_tasks_count: 0 },
    { language: "Others", ann_cumulative_tasks_count: 7, rew_cumulative_tasks_count: 1 },
    { language: "Tamil", ann_cumulative_tasks_count: 165, rew_cumulative_tasks_count: 0 },
    { language: "Telugu", ann_cumulative_tasks_count: 68, rew_cumulative_tasks_count: 0 },
  ],
};