export const info = {
  instruction_data:
    "Imagine you are chatting with an Indian chatbot that can assist you in seeking recommendations related to any topic. Your goal is to interact with the chatbot to fulfill your specific requirement in any domain that you may have. The chatbot will provide suggestions based on your query, be it about buying a product or seeking advice on entertainment options. Make sure to specify your intention clearly and in an Indian context. Please make your interactions in your local language and english script",

  hint: "please interact with LLMs using prompts",

  examples:
    "1. User: Hey, I'm planning to buy a new smartphone, but I'm not sure which one to go for. Can you suggest a good budget-friendly option available in India? 2. User: Hi there! I love binge-watching shows and movies. Could you recommend a popular streaming service that offers a wide range of Indian regional content?",

  meta_info_domain: "None",
  meta_info_intent:
    "seeking some recommendations (for example: I am confused on which gaming laptop to buy. Can you give me some suggestions?)",
  meta_info_language: "Indic language in Latin script",
};

export const chatHistory = [
  {
    prompt:
      "Hey, I'm planning to buy a new smartphone, but I'm not sure which one to go for. Can you suggest a good budget-friendly option available in India?",
    response: {
      output1: 
      "Sure! If you're looking for a budget-friendly smartphone in India, I recommend the Xiaomi Redmi Note 10. It offers great features like a 6.43-inch AMOLED display, a powerful Snapdragon 678 processor, and a decent camera setup at an affordable price. Another option is the Realme Narzo 30 Pro, which also provides good performance and features for its price. Both of these smartphones are popular choices among users in India. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris. Integer in mauris eu nibh euismod gravida. Duis ac tellus et risus vulputate vehicula. Donec lobortis risus a elit. Etiam tempor. Ut ullamcorper, ligula eu tempor congue, eros est euismod turpis, id tincidunt sapien risus a quam. Maecenas fermentum consequat mi. Donec fermentum. Pellentesque malesuada nulla a mi. Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque. Aliquam faucibus, elit ut dictum aliquet, felis nisl adipiscing sapien, sed malesuada diam lacus eget erat. Cras mollis scelerisque nunc. Nullam arcu.",
    output2:
      "Sure! If you're looking for a budget-friendly smartphone in India, I recommend the Xiaomi Redmi Note 10. It offers great features like a 6.43-inch AMOLED display, a powerful Snapdragon 678 processor, and a decent camera setup at an affordable price. Another option is the Realme Narzo 30 Pro, which also provides good performance and features for its price. Both of these smartphones are popular choices among users in India.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris. Integer in mauris eu nibh euismod gravida. Duis ac tellus et risus vulputate vehicula. Donec lobortis risus a elit. Etiam tempor. Ut ullamcorper, ligula eu tempor congue, eros est euismod turpis, id tincidunt sapien risus a quam. Maecenas fermentum consequat mi. Donec fermentum. Pellentesque malesuada nulla a mi. Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque. Aliquam faucibus, elit ut dictum aliquet, felis nisl adipiscing sapien, sed malesuada diam lacus eget erat. Cras mollis scelerisque nunc. Nullam arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris. Integer in mauris eu nibh euismod gravida. Duis ac tellus et risus vulputate vehicula. Donec lobortis risus a elit. Etiam tempor. Ut ullamcorper, ligula eu tempor congue, eros est euismod turpis, id tincidunt sapien risus a quam. Maecenas fermentum consequat mi. Donec fermentum. Pellentesque malesuada nulla a mi. Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque. Aliquam faucibus, elit ut dictum aliquet, felis nisl adipiscing sapien, sed malesuada diam lacus eget erat. Cras mollis scelerisque nunc. Nullam arcu.",
    }
  },
];
