name: Playwright Tests

on:
  push:
    branches:
      - "**" # Runs on any new branch
  pull_request:
    branches:
      - "**" # Runs on any PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 6 # Adjust Node.js version if needed
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
